export const ROLES = {
    ADMIN: "Admin",
    MANAGER: "Manager",
    WAREHOUSE_VN: "WarehouseVN",
    WAREHOUSE_KR: "WarehouseKR",
    ACCOUNTANT: "Accountant",
    EMPLOYEE: "Employee",
    CUSTOMER: "Customer",
} as const;

export const PERMISSIONS = {
    CREATE_ACCOUNT: "CREATE_ACCOUNT",
    MANAGE_ACCOUNT: "MANAGE_ACCOUNT",
    UPDATE_ORDER: "UPDATE_ORDER",
    VIEW_REPORTS: "VIEW_REPORTS",
    DELETE_ACCOUNT: "DELETE_ACCOUNT",
    ASSIGN_ORDER: "ASSIGN_ORDER",
    VIEW_ORDER_HISTORY: "VIEW_ORDER_HISTORY",
    MANAGE_INVENTORY: "MANAGE_INVENTORY",
    MANAGE_CUSTOMER: "MANAGE_CUSTOMER",
    APPROVE_PAYMENT: "APPROVE_PAYMENT",
    MANAGE_SHIPMENTS: "MANAGE_SHIPMENTS",
    VIEW_FINANCIAL_REPORTS: "VIEW_FINANCIAL_REPORTS",
} as const;

export const ROLE_PERMISSIONS = {
    ADMIN: [PERMISSIONS.CREATE_ACCOUNT, PERMISSIONS.MANAGE_ACCOUNT, PERMISSIONS.VIEW_REPORTS],
    MANAGER: [PERMISSIONS.CREATE_ACCOUNT, PERMISSIONS.UPDATE_ORDER],
    CHECKER: [PERMISSIONS.UPDATE_ORDER],
    ACCOUNTANT: [],
} as const;

export type RoleType = typeof ROLES[keyof typeof ROLES];
export type PermissionType = typeof PERMISSIONS[keyof typeof PERMISSIONS]; 
